version: 0.2
phases:
  pre_build:
    commands:
      - pip install pytest
      - echo "[+] Running tests..."
      - python -m pytest tests/ -v
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-1 --no-include-email)
      - REPOSITORY_URI=852056369035.dkr.ecr.us-west-1.amazonaws.com/airflow
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose push      
      - echo Writing image definitions file...
