version: '2'
services:
    webserver:
        image: 852056369035.dkr.ecr.us-west-1.amazonaws.com/airflow:latest
        restart: always
        cpu_shares: 50
        mem_limit: 1048576000
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - FERNET_KEY=tHzPMKdMQOT7OzsKyzfmDX0Xse2Zzk23QzRCohZOpHo=
        ports:
            - "8080:8080"
        command: webserver
        logging:
          driver: awslogs
          options: 
            awslogs-group: airflow
            awslogs-region: us-west-1
            awslogs-stream-prefix: airflow-webserver

    flower:
        image: 852056369035.dkr.ecr.us-west-1.amazonaws.com/airflow:latest
        restart: always
        cpu_shares: 50
        mem_limit: 1048576000
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower
        logging:
          driver: awslogs
          options: 
            awslogs-group: airflow
            awslogs-region: us-west-1
            awslogs-stream-prefix: airflow-flower

    scheduler:
        image: 852056369035.dkr.ecr.us-west-1.amazonaws.com/airflow:latest
        restart: always
        depends_on:
            - webserver
        cpu_shares: 50
        mem_limit: 1048576000
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - FERNET_KEY=tHzPMKdMQOT7OzsKyzfmDX0Xse2Zzk23QzRCohZOpHo=
        command: scheduler
        logging:
          driver: awslogs
          options: 
            awslogs-group: airflow
            awslogs-region: us-west-1
            awslogs-stream-prefix: airflow-scheduler

    worker:
        image: 852056369035.dkr.ecr.us-west-1.amazonaws.com/airflow:latest
        restart: always
        depends_on:
            - webserver
        cpu_shares: 50
        mem_limit: 1048576000
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
            - FERNET_KEY=tHzPMKdMQOT7OzsKyzfmDX0Xse2Zzk23QzRCohZOpHo=
        command: worker
        logging:
          driver: awslogs
          options: 
            awslogs-group: airflow
            awslogs-region: us-west-1
            awslogs-stream-prefix: airflow-worker