name := "twitter-batch"
version := "1.0"
scalaVersion := "2.11.2"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.4"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.4"